version: '3'
services:
  database:
    image: postgres:latest
    container_name: todolist-database
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: todolist-db
    ports:
      - 5432:5432

  backend:
    build: ./backend
    image: todolist-api:latest
    container_name: todolist-backend
    restart: on-failure
    depends_on:
      - database
    env_file:
      - backend-variables.env

  backend-nginx:
    build: ./backend-nginx
    image: todolist-nginx:latest
    container_name: todolist-nginx
    restart: always
    depends_on:
      - backend
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    image: todolist-portal:latest
    container_name: todolist-frontend
    depends_on:
      - backend-nginx
    ports:
      - 80:80